public class Account {
    String RECORD_NUMBER;
    String ACCOUNT_NUMBER;
    String ACCOUNT_TYPE;
    String ACCOUNT_CUSTOMER_ID;
    String ACCOUNT_LIMIT;
    String ACCOUNT_OPEN_DATE;
    String ACCOUNT_BALANCE;

    public Account(String RECORD_NUMBER, String ACCOUNT_NUMBER, String ACCOUNT_TYPE, String ACCOUNT_CUSTOMER_ID, String ACCOUNT_LIMIT, String ACCOUNT_OPEN_DATE, String ACCOUNT_BALANCE) {
        this.RECORD_NUMBER = RECORD_NUMBER;
        this.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
        this.ACCOUNT_TYPE = ACCOUNT_TYPE;
        this.ACCOUNT_CUSTOMER_ID = ACCOUNT_CUSTOMER_ID;
        this.ACCOUNT_LIMIT = ACCOUNT_LIMIT;
        this.ACCOUNT_OPEN_DATE = ACCOUNT_OPEN_DATE;
        this.ACCOUNT_BALANCE = ACCOUNT_BALANCE;
    }
}