public class Customer {
    String RECORD_NUMBER;
    String CUSTOMER_ID;
    String CUSTOMER_NAME;
    String CUSTOMER_SURNAME;
    String CUSTOMER_ADDRESS;
    String CUSTOMER_ZIP_CODE;
    String CUSTOMER_NATIONAL_ID;
    String CUSTOMER_BIRTH_DATE;

    public Customer(String RECORD_NUMBER, String CUSTOMER_ID, String CUSTOMER_NAME, String CUSTOMER_SURNAME, String CUSTOMER_ADDRESS, String CUSTOMER_ZIP_CODE, String CUSTOMER_NATIONAL_ID, String CUSTOMER_BIRTH_DATE) {
        this.RECORD_NUMBER = RECORD_NUMBER;
        this.CUSTOMER_ID = CUSTOMER_ID;
        this.CUSTOMER_NAME = CUSTOMER_NAME;
        this.CUSTOMER_SURNAME = CUSTOMER_SURNAME;
        this.CUSTOMER_ADDRESS = CUSTOMER_ADDRESS;
        this.CUSTOMER_ZIP_CODE = CUSTOMER_ZIP_CODE;
        this.CUSTOMER_NATIONAL_ID = CUSTOMER_NATIONAL_ID;
        this.CUSTOMER_BIRTH_DATE = CUSTOMER_BIRTH_DATE;
    }
}